import Header from "./components/header"
import Footer from "./components/footer"

export const metadata = {
  title: 'Penguin Motors.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
          <Header></Header>
          {children}
          <Footer></Footer>
       </body> 
    </html>
  )
}